from __future__ import annotations

import ast
import os
from pathlib import Path
from typing import Any

from runtime_paths import mykey_path

SECRET_KEYS = {"apikey", "api_key", "secret", "token", "password"}


def classify_kind(var_name: str) -> str:
    name = str(var_name or "").lower()
    if "mixin" in name:
        return "mixin"
    if "native" in name and "claude" in name:
        return "native_claude"
    if "native" in name and "oai" in name:
        return "native_oai"
    if "claude" in name:
        return "claude"
    if "oai" in name:
        return "oai"
    return "unknown"


def _looks_like_config(name: str, value: Any) -> bool:
    if not isinstance(value, dict) or name.startswith("_"):
        return False
    low = name.lower()
    return any(x in low for x in ("api", "config", "cookie")) or any(k in value for k in ("apikey", "apibase", "model", "llm_nos"))


def _literal_assignments(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    out: dict[str, Any] = {}
    for node in tree.body:
        if not isinstance(node, ast.Assign) or len(node.targets) != 1 or not isinstance(node.targets[0], ast.Name):
            continue
        try:
            out[node.targets[0].id] = ast.literal_eval(node.value)
        except Exception:
            continue
    return out


def _mask(value: str) -> str:
    text = str(value or "")
    if len(text) <= 4:
        return "***" if text else ""
    return f"{text[:3]}...{text[-4:]}"


def _mask_dict(data: dict[str, Any]) -> dict[str, Any]:
    out = {}
    for key, value in data.items():
        if key.lower() in SECRET_KEYS and isinstance(value, str):
            out[key] = _mask(value)
        else:
            out[key] = value
    return out


def load_llm_config(mask_secrets: bool = True) -> dict[str, Any]:
    values = _literal_assignments(mykey_path())
    configs = []
    extras = {}
    for name, value in values.items():
        if _looks_like_config(name, value):
            data = dict(value)
            configs.append({"var": name, "kind": classify_kind(name), "data": _mask_dict(data) if mask_secrets else data})
        else:
            extras[name] = value
    return {"configs": configs, "extras": extras, "path": str(mykey_path())}


def _format_dict(data: dict[str, Any]) -> str:
    lines = ["{"]
    for key, value in data.items():
        lines.append(f"    {key!r}: {value!r},")
    lines.append("}")
    return "\n".join(lines)


def save_llm_config(payload: dict[str, Any]) -> dict[str, Any]:
    path = mykey_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    parts = [
        "# mykey.py generated by GenericAgent WebUI\n",
        "# Edit through the web settings page to avoid losing managed fields.\n\n",
    ]
    for item in payload.get("configs") or []:
        var = str(item.get("var") or "").strip()
        if not var:
            continue
        parts.append(f"{var} = {_format_dict(dict(item.get('data') or {}))}\n\n")
    for key, value in dict(payload.get("extras") or {}).items():
        parts.append(f"{key} = {value!r}\n")
    path.write_text("".join(parts), encoding="utf-8")
    os.environ["GA_MYKEY_PATH"] = str(path)
    return load_llm_config(mask_secrets=True)
